name: Sync LeetCode Solutions

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run sync script
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        run: python leetcode_sync.py

      - name: Commit and Push
        run: |
          git config user.name "leetcode-bot"
          git config user.email "bot@example.com"
          git add .
          git commit -m "Update LeetCode submissions" || echo "No changes"
          git push
